# Generated by Django 6.0.7 on 2026-07-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('backtest', 'Backtest Only'), ('paper', 'Paper Trading'), ('live', 'Live Trading')], default='backtest', max_length=20)),
                ('is_enabled', models.BooleanField(default=False, help_text='Master on/off switch for automated trading')),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
                ('real_balance_limit', models.DecimalField(decimal_places=2, default=500.0, max_digits=20)),
                ('max_open_positions', models.IntegerField(default=5)),
                ('max_position_size_pct', models.FloatField(default=10.0, help_text='Max single position as % of balance')),
                ('max_daily_loss_pct', models.FloatField(default=5.0, help_text='Halt trading if daily loss exceeds this %')),
                ('max_drawdown_pct', models.FloatField(default=15.0, help_text='Halt trading if drawdown exceeds this %')),
                ('kelly_fraction', models.CharField(choices=[('full', 'Full Kelly'), ('half', 'Half Kelly'), ('quarter', 'Quarter Kelly')], default='quarter', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quant Configuration',
            },
        ),
        migrations.CreateModel(
            name='FuturesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('funding_rate', models.FloatField(blank=True, null=True)),
                ('open_interest', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('open_interest_quote', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('long_short_ratio', models.FloatField(blank=True, help_text='Long/Short account ratio', null=True)),
                ('taker_buy_vol', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('taker_sell_vol', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('index_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_funding_time', models.DateTimeField(blank=True, null=True)),
                ('next_funding_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Futures data',
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='quant_futur_symbol_3b9f09_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(max_length=5)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('rows_imported', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'interval', 'status'], name='quant_histo_symbol_20228b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('2h', '2 Hours'), ('4h', '4 Hours'), ('6h', '6 Hours'), ('8h', '8 Hours'), ('12h', '12 Hours'), ('1d', '1 Day'), ('3d', '3 Days'), ('1w', '1 Week'), ('1M', '1 Month')], db_index=True, max_length=5)),
                ('open_time', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quote_asset_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('taker_buy_base_vol', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('taker_buy_quote_vol', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('trades', models.IntegerField(blank=True, null=True)),
                ('closed', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'interval', 'open_time'], name='quant_marke_symbol_b13502_idx'), models.Index(fields=['symbol', 'open_time'], name='quant_marke_symbol_cf1bc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'interval', 'open_time'), name='unique_kline')],
            },
        ),
        migrations.CreateModel(
            name='OrderBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('bids_json', models.JSONField(help_text='JSON array of [price, qty] pairs')),
                ('asks_json', models.JSONField(help_text='JSON array of [price, qty] pairs')),
                ('bid_vol', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask_vol', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('imbalance_pct', models.FloatField(blank=True, help_text='bid_vol / (bid_vol + ask_vol) * 100', null=True)),
                ('first_bid_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('first_ask_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='quant_order_symbol_ca5264_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_a', models.CharField(max_length=20)),
                ('symbol_b', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('coint_p_value', models.FloatField(blank=True, null=True)),
                ('coint_statistic', models.FloatField(blank=True, null=True)),
                ('half_life', models.FloatField(blank=True, help_text='Mean reversion half-life in hours', null=True)),
                ('hedge_ratio', models.FloatField(blank=True, null=True)),
                ('current_zscore', models.FloatField(blank=True, null=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_signals', models.IntegerField(default=0)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'coint_p_value'], name='quant_pair_is_acti_6e8e6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol_a', 'symbol_b'), name='unique_pair')],
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('trade_id', models.BigIntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quote_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_buyer_maker', models.BooleanField(help_text='True if buyer is the market maker (sell pressure)')),
                ('is_best_match', models.BooleanField(blank=True, null=True)),
                ('time', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'time'], name='quant_trade_symbol_a5af33_idx'), models.Index(fields=['symbol', 'is_buyer_maker'], name='quant_trade_symbol_7f6eaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('signal_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('neutral', 'Neutral')], max_length=20)),
                ('direction', models.CharField(blank=True, choices=[('long', 'Long'), ('short', 'Short')], max_length=10, null=True)),
                ('strength', models.FloatField(help_text='Signal strength 0.0–1.0')),
                ('confidence', models.FloatField(help_text='Model confidence 0.0–1.0')),
                ('source_model', models.CharField(choices=[('hmm_regime', 'HMM Regime'), ('cointegration', 'Cointegration / Pairs'), ('ml_ensemble', 'ML Ensemble'), ('sentiment', 'Sentiment'), ('orderbook', 'Order Book Imbalance'), ('futures', 'Futures Data'), ('alt_data', 'Alternative Data')], max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expiry', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Additional signal data (e.g., z-score, regime)', null=True)),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quant.pair')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_time', models.DateTimeField(db_index=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('fee_asset', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('paper', 'Paper Trade')], default='open', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('strategy', models.CharField(blank=True, help_text='Which strategy generated this trade', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quant.tradesignal')),
            ],
        ),
        migrations.AddIndex(
            model_name='tradesignal',
            index=models.Index(fields=['symbol', 'status', 'generated_at'], name='quant_trade_symbol_79d657_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesignal',
            index=models.Index(fields=['source_model', 'status'], name='quant_trade_source__2a6653_idx'),
        ),
        migrations.AddIndex(
            model_name='tradesignal',
            index=models.Index(fields=['expiry', 'status'], name='quant_trade_expiry_23a075_idx'),
        ),
        migrations.AddIndex(
            model_name='executedtrade',
            index=models.Index(fields=['symbol', 'entry_time'], name='quant_execu_symbol_8c20f0_idx'),
        ),
        migrations.AddIndex(
            model_name='executedtrade',
            index=models.Index(fields=['status', 'entry_time'], name='quant_execu_status_0b33ab_idx'),
        ),
        migrations.AddIndex(
            model_name='executedtrade',
            index=models.Index(fields=['strategy', 'entry_time'], name='quant_execu_strateg_06c9ea_idx'),
        ),
    ]
