# Generated by Django 6.0.7 on 2026-07-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('hmm_regime', 'HMM Regime Detection'), ('random_forest', 'Random Forest'), ('xgboost', 'XGBoost'), ('ensemble', 'Ensemble'), ('cointegration', 'Cointegration / Pairs')], db_index=True, max_length=30)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(default='1h', max_length=5)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Training parameters used')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Performance metrics from training')),
                ('feature_importance', models.JSONField(blank=True, help_text='Top features by importance', null=True)),
                ('data_points', models.IntegerField(blank=True, null=True)),
                ('feature_count', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Training logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['model_type', 'symbol', '-started_at'], name='quant_train_model_t_16fff9_idx'), models.Index(fields=['-started_at'], name='quant_train_started_558db5_idx')],
            },
        ),
    ]
