# Generated by Django 6.0.7 on 2026-07-21 10:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('backtest', 'Backtest Only'), ('paper', 'Paper Trading'), ('live', 'Live Trading')], default='backtest', max_length=20)),
                ('is_enabled', models.BooleanField(default=False, help_text='Master on/off switch for automated trading')),
                ('virtual_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
                ('real_balance_limit', models.DecimalField(decimal_places=2, default=500.0, max_digits=20)),
                ('max_open_positions', models.IntegerField(default=5)),
                ('max_position_size_pct', models.FloatField(default=10.0, help_text='Max single position as % of balance', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100.0)])),
                ('max_daily_loss_pct', models.FloatField(default=5.0, help_text='Halt trading if daily loss exceeds this %')),
                ('max_drawdown_pct', models.FloatField(default=15.0, help_text='Halt trading if drawdown exceeds this %')),
                ('circuit_breaker_count', models.IntegerField(default=3, help_text='Consecutive losses before circuit breaker trip')),
                ('circuit_breaker_hours', models.IntegerField(default=24, help_text='Hours to wait after circuit breaker trip')),
                ('kelly_fraction', models.FloatField(default=0.25, help_text='Kelly fraction for position sizing (0.25 = Quarter Kelly)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('nightly_optimization_enabled', models.BooleanField(default=False, help_text='Run full optimization cycle nightly')),
                ('min_improvement_threshold', models.FloatField(default=0.05, help_text='Minimum OOS Sharpe improvement to promote new ParamSet (5%)')),
                ('max_trials_per_study', models.IntegerField(default=500, help_text='Max Optuna trials per optimization run')),
                ('default_interval', models.CharField(default='1h', max_length=5)),
                ('max_history_days', models.IntegerField(default=730, help_text='Default historical data window in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Configuration',
            },
        ),
        migrations.CreateModel(
            name='ParamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(help_text="Strategy parameters as JSON (e.g. {'rsi_period': 14, 'ema_fast': 9})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_live', models.BooleanField(default=False, help_text='Currently deployed in paper/live trading')),
                ('is_candidate', models.BooleanField(default=False, help_text='Candidate for promotion (beating current live on OOS metrics)')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Performance metrics: sharpe, sortino, win_rate, profit_factor, max_dd, expectancy')),
            ],
            options={
                'ordering': ['-is_live', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this strategy is currently generating signals')),
                ('strategy_class', models.CharField(help_text='Python import path (e.g. trading_bot.services.strategies.technical.MomentumStrategy)', max_length=200)),
                ('weight', models.FloatField(default=1.0, help_text='Dynamic ensemble weight (updated by promoter)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Strategies',
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('config_change', 'Configuration Change'), ('signal_generated', 'Signal Generated'), ('trade_opened', 'Trade Opened'), ('trade_closed', 'Trade Closed'), ('param_promoted', 'Parameter Set Promoted'), ('optimization_run', 'Optimization Run'), ('error', 'Error / Circuit Breaker'), ('info', 'Information')], db_index=True, max_length=30)),
                ('message', models.TextField(help_text='Human-readable description of what happened')),
                ('details', models.JSONField(blank=True, help_text='Structured data: trade IDs, signal IDs, metric values, etc.', null=True)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='trading_bot_action_721161_idx'), models.Index(fields=['severity', '-timestamp'], name='trading_bot_severit_946fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(default='1h', max_length=5)),
                ('feature_set_version', models.CharField(default='1.0', help_text='Version of the feature pipeline that generated this snapshot', max_length=20)),
                ('features', models.JSONField(help_text='Feature name → value dictionary. Keys are feature names, values are floats.')),
                ('source_hash', models.CharField(blank=True, help_text='SHA-256 of input data used to generate features (reproducibility)', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'feature_set_version', '-timestamp'], name='trading_bot_symbol_f70e43_idx'), models.Index(fields=['symbol', 'interval', '-timestamp'], name='trading_bot_symbol_031b87_idx')],
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, default='binance', help_text='Exchange identifier (binance, coinbase, kraken, etc.)', max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(choices=[('1s', '1 Second'), ('5s', '5 Seconds'), ('15s', '15 Seconds'), ('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('2h', '2 Hours'), ('4h', '4 Hours'), ('6h', '6 Hours'), ('8h', '8 Hours'), ('12h', '12 Hours'), ('1d', '1 Day'), ('3d', '3 Days'), ('1w', '1 Week')], db_index=True, max_length=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=24)),
                ('quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('trades', models.IntegerField(blank=True, null=True)),
                ('taker_buy_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('taker_buy_quote_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('closed', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OHLCV',
                'verbose_name_plural': 'OHLCV Data',
                'indexes': [models.Index(fields=['exchange', 'symbol', 'interval', 'timestamp'], name='trading_bot_exchang_04ea65_idx'), models.Index(fields=['symbol', 'interval', '-timestamp'], name='trading_bot_symbol_cf5075_idx')],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'symbol', 'interval', 'timestamp'), name='unique_ohlcv_candle')],
            },
        ),
        migrations.CreateModel(
            name='OrderBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default='binance', max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('bids', models.JSONField(help_text='JSON array of [price, quantity] arrays, sorted best bid first')),
                ('asks', models.JSONField(help_text='JSON array of [price, quantity] arrays, sorted best ask first')),
                ('bid_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('ask_volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('spread', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('spread_pct', models.FloatField(blank=True, null=True)),
                ('imbalance_pct', models.FloatField(blank=True, help_text='bid_volume / (bid_volume + ask_volume) * 100', null=True)),
                ('depth_pressure', models.FloatField(blank=True, help_text='(bid_top5 - ask_top5) / (bid_top5 + ask_top5)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='trading_bot_symbol_11cffe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('direction', models.SmallIntegerField(choices=[(1, 'Long'), (0, 'Neutral'), (-1, 'Short')])),
                ('confidence', models.FloatField(help_text='Model confidence / signal strength', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('features_used', models.JSONField(blank=True, help_text='List of feature names that contributed to this signal', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('filled', 'Filled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context (regime state, market conditions, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('param_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='trading_bot.paramset')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='trading_bot.strategy')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='paramset',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_sets', to='trading_bot.strategy'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('paper', 'Paper Trade'), ('live', 'Live Trade')], db_index=True, max_length=10)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_time', models.DateTimeField(db_index=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, help_text='Realized PnL in quote currency', max_digits=20, null=True)),
                ('pnl_pct', models.FloatField(blank=True, help_text='PnL as percentage of entry value', null=True)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exit_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('slippage', models.DecimalField(blank=True, decimal_places=8, help_text='Estimated slippage for paper trades', max_digits=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exchange_order_id', models.CharField(blank=True, help_text='Exchange order ID (live trades only)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('param_set', models.ForeignKey(blank=True, help_text='ParamSet used when this trade was opened', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading_bot.paramset')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading_bot.signal')),
                ('strategy', models.ForeignKey(blank=True, help_text='Strategy that generated this trade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading_bot.strategy')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(default='1h', max_length=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Full metrics: sharpe, sortino, calmar, win_rate, profit_factor, max_dd, expectancy, total_trades, avg_hold_time, etc.')),
                ('equity_curve', models.JSONField(blank=True, help_text='JSON array of [timestamp_epoch, equity] pairs', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('param_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='trading_bot.paramset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['param_set', 'symbol', '-created_at'], name='trading_bot_param_s_031629_idx'), models.Index(fields=['status', '-created_at'], name='trading_bot_status_c6a5d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['symbol', 'status', '-timestamp'], name='trading_bot_symbol_2ff0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['strategy', 'status'], name='trading_bot_strateg_fc4c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['-timestamp'], name='trading_bot_timesta_035ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='paramset',
            index=models.Index(fields=['strategy', '-created_at'], name='trading_bot_strateg_c1d47d_idx'),
        ),
        migrations.AddIndex(
            model_name='paramset',
            index=models.Index(fields=['is_live', 'is_candidate'], name='trading_bot_is_live_1dcd08_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', 'status', '-entry_time'], name='trading_bot_symbol_0cb6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['mode', 'status'], name='trading_bot_mode_2e7b74_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['strategy', '-entry_time'], name='trading_bot_strateg_1ad5b8_idx'),
        ),
    ]
