# Generated by Django 6.0.7 on 2026-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Your Google Gemini API key from https://aistudio.google.com/apikey', max_length=512, verbose_name='API Key')),
                ('model', models.CharField(choices=[('gemini-2.5-pro-exp-03-25', 'Gemini 2.5 Pro (Experimental) — Best reasoning'), ('gemini-2.0-flash', 'Gemini 2.0 Flash — Best overall balance'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash-Lite — Faster, lighter'), ('gemini-1.5-flash', 'Gemini 1.5 Flash — Older but reliable'), ('gemini-1.5-flash-8b', 'Gemini 1.5 Flash-8B — Fastest, most compact')], default='gemini-2.0-flash', help_text='Select a free Gemini model. Ranked best → worst.', max_length=128, verbose_name='AI Model')),
                ('custom_model', models.CharField(blank=True, default='', help_text='Override the dropdown. Enter any model name (e.g. gemini-2.0-flash-001). If set, this is used instead of the dropdown selection.', max_length=128, verbose_name='Custom Model (Optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this configuration', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google AI Configuration',
                'verbose_name_plural': 'Google AI Configurations',
            },
        ),
    ]
