# Generated by Django 6.0.7 on 2026-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. gemini-3.5-flash', max_length=128, unique=True, verbose_name='Model Name')),
                ('rank', models.PositiveIntegerField(default=999, help_text='Lower number = higher priority. 1 = best model, tried first.', verbose_name='Priority Rank')),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable description of the model.', max_length=256, verbose_name='Display Label')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to skip this model during fallback attempts.', verbose_name='Active in Fallback Chain')),
                ('auto_discovered', models.BooleanField(default=False, help_text='Was this model automatically found via the Google API?', verbose_name='Auto-Discovered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gemini Model',
                'verbose_name_plural': 'Gemini Models',
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='custom_model',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='model',
        ),
    ]
