# Generated by Django 6.0.7 on 2026-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Your Binance API key', max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(help_text='Your Binance API secret key', max_length=512, verbose_name='API Secret')),
                ('use_testnet', models.BooleanField(default=False, help_text='Enable to use Binance testnet (for development/testing)', verbose_name='Use Testnet')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this configuration', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Binance API Configuration',
                'verbose_name_plural': 'Binance API Configurations',
            },
        ),
    ]
